require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
target 'ChristFellowship' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  # pod 'react-native-google-cast/NoBluetooth', path: '../node_modules/react-native-google-cast/ios/'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'ChristFellowshipTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  
  post_install do |installer|
    # flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
    end    
  end
end

target 'ChristFellowship-tvOS' do
  # Pods for ChristFellowship-tvOS

  target 'ChristFellowship-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end

end
